@echo off
echo Launching Boomr Game (ES3.1)...
start "" "C:\Program Files\Epic Games\UE_4.27\Engine\Binaries\Win64\UE4Editor.exe" "%~dp0..\Boomr.uproject" -game -featureleveles31 -windowed -ResX=1280 -ResY=720
